/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/embedding": {
    /**
     * Embedding
     * @description 文章を受け取り、ベクトル化した結果を返すAPI
     */
    post: operations["embedding_embedding_post"];
  };
  "/doc": {
    /**
     * Documents
     * @description ドキュメントの一覧
     */
    get: operations["documents_doc_get"];
  };
  "/doc/{id}": {
    /**
     * Document
     * @description ドキュメントを1つ返す
     */
    get: operations["document_doc__id__get"];
  };
  "/cluster": {
    /**
     * Cluster Index
     * @description クラスターの一覧
     */
    get: operations["cluster_index_cluster_get"];
  };
  "/cluster/{cluster}": {
    /**
     * Get Cluster
     * @description クラスタに属するドキュメントを返す
     */
    get: operations["get_cluster_cluster__cluster__get"];
  };
  "/search": {
    /**
     * Search
     * @description 文章を受け取り、類似度の高い文章を返す
     */
    get: operations["search_search_get"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    /** Doc */
    Doc: {
      /** Id */
      id: number;
      /** Volume Title */
      volume_title: string;
      /** Chapter Title */
      chapter_title: string;
      /** Section Number */
      section_number: string;
      /** Content */
      content: string;
    };
    /** DocListItem */
    DocListItem: {
      /** Id */
      id: number;
      /** Volume Title */
      volume_title: string;
      /** Chapter Title */
      chapter_title: string;
      /** Section Number */
      section_number: string;
    };
    /** EmbeddingParams */
    EmbeddingParams: {
      /** Sentence */
      sentence: string;
    };
    /** EmbeddingResponse */
    EmbeddingResponse: {
      /** Embedding */
      embedding: number[];
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /** ScoredDoc */
    ScoredDoc: {
      document: components["schemas"]["Doc"];
      /** Score */
      score: number;
    };
    /** SearchResponse */
    SearchResponse: {
      /** Result */
      result: components["schemas"]["ScoredDoc"][];
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  /**
   * Embedding
   * @description 文章を受け取り、ベクトル化した結果を返すAPI
   */
  embedding_embedding_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["EmbeddingParams"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["EmbeddingResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Documents
   * @description ドキュメントの一覧
   */
  documents_doc_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["DocListItem"][];
        };
      };
    };
  };
  /**
   * Document
   * @description ドキュメントを1つ返す
   */
  document_doc__id__get: {
    parameters: {
      path: {
        id: number;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["Doc"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Cluster Index
   * @description クラスターの一覧
   */
  cluster_index_cluster_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  /**
   * Get Cluster
   * @description クラスタに属するドキュメントを返す
   */
  get_cluster_cluster__cluster__get: {
    parameters: {
      path: {
        cluster: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Search
   * @description 文章を受け取り、類似度の高い文章を返す
   */
  search_search_get: {
    parameters: {
      query: {
        q: string;
        top_k?: number;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["SearchResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
}
