# fly.toml file generated for sangokushi-gpt-qdrant on 2023-04-06T20:50:48+09:00

app = "sangokushi-gpt-qdrant"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "nrt"

[metrics]
  path = "/metrics"
  port = 9091

[mounts]
  destination = "/qdrant/storage"
  source = "sangokushi_gpt_qdrant_storage"
