version: '3.7'
services:
  qdrant:
    build:
      context: qdrant
      args:
        - ENV=development
    restart: always
    ports:
      - 6333:6333
    volumes:
      - ./qdrant-storage:/qdrant/storage
