version: '3.7'
services:
  qdrant:
    build:
      context: qdrant
      args:
        - ENV=development
    restart: always
    ports:
      - 6333:6333
    volumes:
      - ./qdrant-storage:/qdrant/storage

  embedding-api:
    image: coji/simcse-embedding-api:latest
    restart: always
    environment:
      - PORT=8080
      - HOST=0.0.0.0
    ports:
      - 8080:8080
    volumes:
      - ./embedding-api-cache:/root/.cache
