# fly.toml file generated for sangokushi-gpt on 2023-03-30T22:53:47+09:00

app = "sangokushi-gpt"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "nrt"
processes = []

[env]
  PORT = "8080"

[experimental]
  auto_rollback = true

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

  [http_service.concurrency]
    type = "requests"
    soft_limit = 200
    hard_limit = 250
