[project]
name = "api"
version = "0.1.0"
description = "Add your description here"
authors = [
    { name = "coji", email = "coji@techtalk.jp" }
]
dependencies = [
    "sentence-transformers>=2.2.2",
    "fugashi[unidic-lite]>=1.2.1",
    "fastapi>=0.101.1",
    "pydantic>=2.2.1",
    "uvicorn[standard]>=0.23.2",
    "torch==2.0.1",
    "hyperdb-python>=0.1.4",
]
readme = "README.md"
requires-python = ">= 3.8"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.rye]
managed = true
dev-dependencies = [
    "black>=23.7.0",
]

[[tool.rye.sources]]
name = "torch"
url = "https://download.pytorch.org/whl/cpu"
type = "index"

[tool.rye.scripts]
start = { cmd = 'uvicorn server:app --reload --host 0.0.0.0 --port 8000', env = { ENV = 'development' } }
"docker:build" = { chain = ["docker:build:image", "docker:build:tag"] }
"docker:build:image" = { cmd = 'docker build -t litefs-speedrun-api .' }
"docker:build:tag" = { cmd = 'docker tag litefs-speedrun-api coji/litefs-speedrun-api:latest' }
"docker:push" = { cmd = 'docker push coji/litefs-speedrun-api:latest' }

[tool.hatch.metadata]
allow-direct-references = true
